export const siteConfig = {
  name: "Coimagen Media Agency",
  tagline: "Marketing + Automation + AI Agents + Business Operating Systems",
  domain: "www.coimagenmedia.com",
  portalUrl: "https://coimagenmediaos.replit.app/",
  whatsapp: {
    number: "15559318378",
    display: "+1 555 931 8378",
    url: "https://wa.me/+15559318378",
  },
  email: "contacto@coimagenmedia.com",
  location: "Tijuana / San Diego",
  social: {
    facebook: "https://www.facebook.com/coimagenmediaagency/",
    facebookHandle: "Coimagen Media Agency",
    instagram: "https://www.instagram.com/coimagenmediaagency/",
    instagramHandle: "@coimagenmedia",
    linkedin: "#",
    youtube: "#",
    tiktok: "#",
  },
  founder: {
    name: "Camila Segovia",
    title: {
      es: "CEO de Coimagen Media",
      en: "CEO of Coimagen Media",
    },
  },
  caseStudies: [
    {
      slug: "dr-segovia",
      labelEs: "Dr. José Manuel Segovia",
      labelEn: "Dr. José Manuel Segovia",
      industryEs: "Neurocirugía",
      industryEn: "Neurosurgery",
      liveUrl: "",
    },
    {
      slug: "chimichimi",
      labelEs: "Chimichimi Restaurant",
      labelEn: "Chimichimi Restaurant",
      industryEs: "Restaurante",
      industryEn: "Restaurant",
      liveUrl: "",
    },
    {
      slug: "coimagen-os",
      labelEs: "COIMAGEN OS",
      labelEn: "COIMAGEN OS",
      industryEs: "SaaS / Tecnología",
      industryEn: "SaaS / Technology",
      liveUrl: "https://coimagenmediaos.replit.app/",
    },
    {
      slug: "conchas-tower",
      labelEs: "Conchas Tower",
      labelEn: "Conchas Tower",
      industryEs: "Bienes Raíces",
      industryEn: "Real Estate",
      liveUrl: "",
    },
  ],
  servicePages: [
    {
      slug: "ai-powered-websites",
      labelEs: "AI Powered Websites",
      labelEn: "AI Powered Websites",
      descEs: "Sitios web con IA",
      descEn: "Websites powered by AI",
      icon: "🖥️",
      color: "cyan",
    },
    {
      slug: "seo-growth",
      labelEs: "SEO Growth",
      labelEn: "SEO Growth",
      descEs: "Posicionamiento en Google",
      descEn: "Google ranking system",
      icon: "🚀",
      color: "lime",
    },
    {
      slug: "google-business-optimization",
      labelEs: "Google Business",
      labelEn: "Google Business",
      descEs: "Optimización local",
      descEn: "Local optimization",
      icon: "🗺️",
      color: "yellow",
    },
    {
      slug: "ai-automation",
      labelEs: "AI Automation",
      labelEn: "AI Automation",
      descEs: "Automatización con IA",
      descEn: "Automation with AI",
      icon: "⚡",
      color: "purple",
    },
    {
      slug: "ai-agents",
      labelEs: "AI Agents",
      labelEn: "AI Agents",
      descEs: "Agentes de IA",
      descEn: "AI agents for business",
      icon: "🤖",
      color: "cyan",
    },
    {
      slug: "camila-ai",
      labelEs: "Camila AI",
      labelEn: "Camila AI",
      descEs: "Tu asistente digital",
      descEn: "Your digital assistant",
      icon: "💬",
      color: "lime",
    },
    {
      slug: "coimagen-os",
      labelEs: "COIMAGEN OS",
      labelEn: "COIMAGEN OS",
      descEs: "Sistema operativo empresarial",
      descEn: "Business operating system",
      icon: "⭐",
      color: "purple",
    },
    {
      slug: "cloud-systems",
      labelEs: "Cloud Systems",
      labelEn: "Cloud Systems",
      descEs: "Infraestructura en la nube",
      descEn: "Cloud infrastructure",
      icon: "☁️",
      color: "cyan",
    },
  ],
  industryPages: [
    { slug: "medical-os", labelEs: "Medical OS", labelEn: "Medical OS", tagEs: "Médicos", tagEn: "Doctors" },
    { slug: "dental-os", labelEs: "Dental OS", labelEn: "Dental OS", tagEs: "Dentistas", tagEn: "Dentists" },
    { slug: "law-os", labelEs: "Law OS", labelEn: "Law OS", tagEs: "Abogados", tagEn: "Law Firms" },
    { slug: "wellness-os", labelEs: "Wellness OS", labelEn: "Wellness OS", tagEs: "Estéticas & Bienestar", tagEn: "Wellness & Beauty" },
    { slug: "restaurant-os", labelEs: "Restaurant OS", labelEn: "Restaurant OS", tagEs: "Restaurantes", tagEn: "Restaurants" },
    { slug: "real-estate-os", labelEs: "Real Estate OS", labelEn: "Real Estate OS", tagEs: "Inmobiliarias", tagEn: "Realtors" },
    { slug: "local-business-os", labelEs: "Local Business OS", labelEn: "Local Business OS", tagEs: "Negocios Locales", tagEn: "Local Businesses" },
  ],
};

export type Lang = "es" | "en";
export type Country = "mx" | "usa";
